import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter,Pixelify_Sans,Jersey_10 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import ThemeProvider from "./ThemeProvider";
import {ClerkProvider} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const gameFont = Jersey_10({
    subsets: ["latin"],
    variable: '--font-game',
    weight: ['400']
})

const inter = Inter({
   subsets: ["latin"],
    variable: '--font-inter'
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

     
  return (
     <ClerkProvider>
         <html
      lang="en"
      className={cn("h-full", "antialiased", "dark",geistSans.variable, geistMono.variable, "font-sans", inter.variable, gameFont.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
          <ThemeProvider 
             attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
           >
               {children}
          </ThemeProvider>
        
        </body>
    </html>

     </ClerkProvider>
  );
}
